# Generated by Django 2.2.4 on 2019-08-11 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=40)),
                ('location', models.CharField(max_length=40)),
                ('experience', models.CharField(max_length=40)),
                ('primary_skill', models.CharField(max_length=120)),
                ('secondary_skill', models.CharField(max_length=120)),
                ('salary', models.CharField(max_length=60)),
                ('job_description', models.TextField()),
                ('posted_on', models.DateField(auto_now_add=True)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
    ]
