# Generated by Django 2.2.4 on 2019-08-11 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_portal', '0002_auto_20190811_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='slug',
            field=models.SlugField(blank=True, editable=False, unique=True),
        ),
    ]
