# Generated by Django 2.2.4 on 2019-08-12 14:43

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job_portal', '0003_auto_20190811_1400'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='enter a valid phone number.', regex='^[0-9]{10}$')])),
                ('experience', models.CharField(max_length=40)),
                ('skills', models.CharField(max_length=120)),
                ('resume', models.FileField(upload_to='resume/')),
                ('status', models.CharField(choices=[('rejected', 'Rejected'), ('accepted', 'Accepted'), ('pending', 'Pending')], default='pending', max_length=30)),
                ('applied_for', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job_portal.JobPost')),
            ],
        ),
    ]
