# Generated by Django 2.2.4 on 2019-08-11 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job_portal', '0003_auto_20190811_1400'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('experience', models.CharField(max_length=40)),
                ('skills', models.CharField(max_length=120)),
                ('resume', models.FileField(upload_to='resume/')),
                ('applied_for', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job_portal.JobPost')),
            ],
        ),
    ]
