# Generated by Django 2.2.4 on 2019-08-11 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_portal', '0004_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('rejected', 'Rejected'), ('accepted', 'Accepted'), ('pending', 'Pending')], default='pending', max_length=30),
        ),
    ]
